### ISSUE TITLE
Demo App is stuck - getting 304 from GET /authy/status

### ISSUE THREAD

**Issue by benedictkohtc** [TwilioDevEd/authy2fa-node#11]
Hi,

I'm stuck on the demo app.
I manage to register a test account and receive the registration SMS. However when I try to login, the app gets stuck.

Front end shows `Awaiting One Touch approval.`
Server shows a never-ending series of requests to `"GET /authy/status HTTP/1.1"` with a 304 response.
ngrok also shows  `GET /authy/status              304 Not Modified`

**Comment by joliveros** [comment]
Hi @benedictkohtc, 

This repo seems to be out of date. There is a newer tutorial regarding Authy here if you want to check it out:

https://github.com/TwilioDevEd/account-security-quickstart-node
