### ISSUE TITLE
Error: getaddrinfo ENOTFOUND undefined undefined:27017

### ISSUE THREAD

**Issue by pythonl1** [TwilioDevEd/authy2fa-node#7]
Hi,

I am getting the above error while trying to run the server.

Here is the trackback for the step.

```
manprax@mxbhartendu:~/authy2fa-node$ node .
Express server started on *:3000

/home/manprax/authy2fa-node/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: getaddrinfo ENOTFOUND undefined undefined:27017
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

I was following the instructions provided in the README.md file.

**Comment by MihaelN** [comment]
I have the same issue, is there any known solution?

**Comment by philnash** [comment]
I am so sorry, I only just saw this issue after the comment this morning.

Anyway, it looks to me as though you do not have MongoDB running or it is running and on a different port number to the default (27017).

Can you confirm whether you have MongoDB and can access it on localhost:27017.

**Comment by dprothero** [comment]
The application is looking for an environment variable `MONGO_URL`. It works for me if you set the URL to "mongodb://127.0.0.1:27017". I will update the README.

**Comment by NanoArtZ** [comment]
after restart my router / internet connection , its worked. try that
